coverage:
  status:
    project:
      default:
        # basic
        target: 100%
        threshold: 0%
        base: auto 
        flags: 
          - unit
        paths: 
          - "topics"
       # advanced
        branches: 
          - master
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch:
      default:
        # basic
        target: 100%
        threshold: 0%
        base: auto 
        # advanced
        branches: 
          - master
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        paths: 
          - "topics"
