version: "3"
services:
  app:
    container_name: hacker
    image: nguyennguyen/hacker
    stdin_open: true
    tty: true
    volumes: 
      - ./:/app
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
      